#!/usr/bin/env bash
# This hook is run after a new virtualenv is activated.
# ~/.virtualenvs/postmkvirtualenv

function find_real_lib {
    syspy=$1
    libname=$2
    syspath=$($syspy -c "import sys; print(' '.join(sys.path).strip())")
    for libdir in $syspath; do
        if [ -e $libdir/$libname ]; then
            eval "$3=$libdir/$libname"
            return 0
        fi 
    done
    return 1
}

libs=( PyQt5 sip.so sip.cpython-34m-x86_64-linux-gnu.so vtk cairo OpenGL)
#libs=( vtk cairo )

python_version=python$(python -c "import sys; print (str(sys.version_info[0])+'.'+str(sys.version_info[1]))")
var=( $(which -a $python_version) )
syspy=${var[-1]}

get_python_lib_cmd="from distutils.sysconfig import get_python_lib; print (get_python_lib())"
lib_virtualenv_path=$(python -c "$get_python_lib_cmd")

for lib in ${libs[@]}
do
    libsyspath=''
    find_real_lib $syspy $lib libsyspath
    if [ $? == '0' ]; then
        echo "Linking $lib"
        ln -s $libsyspath $lib_virtualenv_path/$lib
    else
        echo "Could not find system's $lib"
    fi
done

